name: AdvancedScope
version: ${project.version}
main: advancedscope.advancedscope.AdvancedScope
description: CS武器のズーム時のスコープのテクスチャをカスタマイズできるようにするPluginです
depend:
  - CrackShot

commands:
  ads:
    usage:  /ads
    description: AdvancedScopeのCommand